template = "https://github.com/giellalt/template-lang-und"
rev_id = 305
template_sha = "64df68fecb78cef7f709bfe67c09affe7c3b0c38"

[replacements]
__GLOTTOLOG_ID__ = "sout2679"
__REPO__ = "lang-vro"
__UND2C__ = "vro"
__UNDEFINED__ = "Võro"
__UND__ = "vro"
