template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "b019fafa945ec21f8f1ee983a95aba800ec89260"

[replacements]
__GLOTTOLOG_ID__ = "sout2679"
__REPO__ = "lang-vro"
__UND2C__ = "vro"
__UNDEFINED__ = "Võro"
__UND__ = "vro"
