template = "https://github.com/giellalt/template-lang-und"
rev_id = 338
template_sha = "f8f3c0370220064ccae6868bc90707e0583f91c2"

[replacements]
__GLOTTOLOG_ID__ = "sout2679"
__REPO__ = "lang-vro"
__UND2C__ = "vro"
__UNDEFINED__ = "Võro"
__UND__ = "vro"
